<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CronSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed data for your table
        DB::table('cron_schedules')->truncate();
        DB::table('cron_schedules')->insert(
            [
                [
                    'command_name' => 'promodata-fetch-product-types',
                    'description' => 'Fetch and insert product types from Promodata API to the database',
                    'schedule' => '30 13 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-categories',
                    'description' => 'Create categories on magento',
                    'schedule' => '40 13 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-sub-categories',
                    'description' => 'Create sub categories on magento',
                    'schedule' => '50 13 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-update-products',
                    'description' => 'Update products from Promodata API to the database',
                    'schedule' => '00 14 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'laravel-remove-different-hero-images',
                    'description' => 'This command will removes the old hero images from laravel panel',
                    'schedule' => '30 14 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'laravel-remove-different-other-images',
                    'description' => 'This command will removes the old other images from laravel panel',
                    'schedule' => '00 15 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'laravel-remove-different-colour-images',
                    'description' => 'This command will removes the old colour images from laravel panel',
                    'schedule' => '30 15 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-download-product-color-list',
                    'description' => 'Command to download color list of the products.',
                    'schedule' => '00 16 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-download-product-hero-images',
                    'description' => 'Download and store product hero images from Promo data',
                    'schedule' => '30 16 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-download-product-media',
                    'description' => 'Command to download product images or medias',
                    'schedule' => '00 17 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-post-product',
                    'description' => 'Post product to magento admin',
                    'schedule' => '30 17 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'update-product-magento-id',
                    'description' => 'Update magento id to product table',
                    'schedule' => '00 18 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-custom-options',
                    'description' => 'Create product custom options using variants and additions',
                    'schedule' => '30 18 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-hero-images',
                    'description' => 'Upload hero images to magento products',
                    'schedule' => '00 19 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-other-images',
                    'description' => 'Upload other media to magento products',
                    'schedule' => '10 19 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-colours-images',
                    'description' => 'Upload colour images to magento products',
                    'schedule' => '20 19 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-update-product',
                    'description' => 'Update products of promodata to magento database',
                    'schedule' => '30 19 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-update-custom-options',
                    'description' => 'Update custom options of promodata to magento database',
                    'schedule' => '00 20 * * 1',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-fetch-product-types',
                    'description' => 'Fetch and insert product types from Promodata API to the database',
                    'schedule' => '30 13 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-categories',
                    'description' => 'Create categories on magento',
                    'schedule' => '40 13 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-sub-categories',
                    'description' => 'Create sub categories on magento',
                    'schedule' => '50 13 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-update-products',
                    'description' => 'Update products from Promodata API to the database',
                    'schedule' => '00 14 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'laravel-remove-different-hero-images',
                    'description' => 'This command will removes the old hero images from laravel panel',
                    'schedule' => '30 14 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'laravel-remove-different-other-images',
                    'description' => 'This command will removes the old other images from laravel panel',
                    'schedule' => '00 15 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'laravel-remove-different-colour-images',
                    'description' => 'This command will removes the old colour images from laravel panel',
                    'schedule' => '30 15 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-download-product-color-list',
                    'description' => 'Command to download color list of the products.',
                    'schedule' => '00 16 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-download-product-hero-images',
                    'description' => 'Download and store product hero images from Promo data',
                    'schedule' => '30 16 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'promodata-download-product-media',
                    'description' => 'Command to download product images or medias',
                    'schedule' => '00 17 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-post-product',
                    'description' => 'Post product to magento admin',
                    'schedule' => '30 17 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'update-product-magento-id',
                    'description' => 'Update magento id to product table',
                    'schedule' => '00 18 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-custom-options',
                    'description' => 'Create product custom options using variants and additions',
                    'schedule' => '30 18 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-hero-images',
                    'description' => 'Upload hero images to magento products',
                    'schedule' => '00 19 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-other-images',
                    'description' => 'Upload other media to magento products',
                    'schedule' => '10 19 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-colours-images',
                    'description' => 'Upload colour images to magento products',
                    'schedule' => '20 19 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-update-product',
                    'description' => 'Update products of promodata to magento database',
                    'schedule' => '30 19 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-update-custom-options',
                    'description' => 'Update custom options of promodata to magento database',
                    'schedule' => '00 20 * * 4',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-bulk-product-custom-option-update',
                    'description' => 'This command will update bulk product custom options based on magento updated at field',
                    'schedule' => '00 11 * * *',
                    'status' => '0',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-post-products-based-on-bulk-action',
                    'description' => 'Post product to magento based on bulk action with product updated_at date',
                    'schedule' => '00 12 * * *',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-create-custom-options-based-on-bulk-action',
                    'description' => 'Create product custom options based on bulk action with updated_at date of product',
                    'schedule' => '10 12 * * *',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-hero-images-based-on-bulk-action',
                    'description' => 'Upload images to magento products based on bulk action with updated_at date of product',
                    'schedule' => '20 12 * * *',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-other-images-based-on-bulk-action',
                    'description' => 'Upload other media to magento products based on bulk action with updated_at date of product',
                    'schedule' => '30 12 * * *',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-upload-colours-images-based-on-bulk-action',
                    'description' => 'Upload colour images to magento products based on bulk action with updated_at date of product',
                    'schedule' => '40 12 * * *',
                    'status' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'command_name' => 'magento-update-product-manual',
                    'description' => 'This command will update bulk product custom options based on magento updated at field',
                    'schedule' => '* * * * *',
                    'status' => '0',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
